
#' Phenotypic list demo data.
#'
#' Contains the test data of different periods, regions and communities.
#'
#' @format A Large matrix with 31689 elements(By asreml::ainverse):
"phdemo"


#' Blue list data.
#'
#'
#' @format A list Blue value with "EM" "ML" "SU" "SW":
"bluelist"

#' Pedigree data in ASREML format.
#'
#' This data can be generated by asreml::ainverse(PED).
#'
#' @format A Large matrix with 31689 elements(By asreml::ainverse):
"ainv"

#' Pedigree data.
#'
#' Original pedigree data corresponding to test pheno data.
#'
#' @format A data frame with 2820 rows and 3 variables:
#' \describe{
#'   \item{ID}{Individual ID}
#'   \item{FGenoId}{Male parent ID}
#'   \item{MGenoId}{Female parent ID}
#' }
"ped"

#' Aov data.
#'
#'
#' @format Variance test table:
"Aov"

#' popmean data.
#'
#'
#' @format Population average table:
"popmean"

#' adv data.
#'
#'
#' @format adv table:
"adv"

#' hybobs data.
#'
#'
#' @format hybobs table:
"hybobs"

#' blupebv breeding value.
#'
#'
#' @format blupebv breeding value table:
"blupebv"
